CREATE TABLE "MW_app"."SS_ROLE" 
   (  "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"PERMISSIONS" VARCHAR2(255)
   ) 

CREATE TABLE "MW_app"."SS_TEAM" 
   (  "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255), 
	"MASTER_ID" NUMBER
   )

CREATE TABLE "MW_app"."SS_USER" 
   (  "ID" NUMBER NOT NULL ENABLE, 
	"LOGIN_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"NAME" VARCHAR2(64), 
	"PASSWORD" VARCHAR2(255), 
	"SALT" VARCHAR2(64), 
	"EMAIL" VARCHAR2(128), 
	"STATUS" VARCHAR2(32), 
	"TEAM_ID" NUMBER
   )

CREATE TABLE "MW_app"."SS_USER_ROLE" 
   (  "USER_ID" NUMBER NOT NULL ENABLE, 
	"ROLE_ID" NUMBER NOT NULL ENABLE
   )
